# -*- coding: utf-8 -*-
"""Diffusion Ising Termo Fidelity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wy3CiQHZdAQ55oVsDhU6cJq6Iqr-fiwu

Clone repository implementing forward and backward difussion process.
"""

# Commented out IPython magic to ensure Python compatibility.
## Ising fidelity
# !git clone https://github.com/htapia/generative_models_Ising.git

import numpy as np
import plotly.graph_objects as go
import time
import copy
import matplotlib.pyplot as plt
from numpy import random
# from numba import jit
from google.colab import files
import json
import gc

import torch
import torch.nn as nn
from tqdm import tqdm
from torch import optim
from torch.utils.data import DataLoader, TensorDataset

import os
# os.system('rm -rf generative_models_Ising')
# os.system("git clone https://github.com/htapia/generative_models_Ising.git")
# os.system('cd /content/generative_models_Ising/diffusion/')
os.chdir("/content/generative_models_Ising/diffusion/")

from modules import UNet_conditional, Diffusion
# from google.colab import drive
# drive.mount('/content/drive')

boards_url = 'train_data'
# os.listdir(boards_url)
# Setup training parameters
# Load Ising data generated in the previous section

# cdevice.reset()
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
imgsize = 128
batch_size = 2
nepoch=50
nfreq=10
lr=3e-4
config_file = boards_url +'/ising_50configs{}.json'.format(imgsize)

with open(config_file, 'r') as f:
    data = json.load(f)
ising_data = np.array([np.array(d['config']) for d in data])
temperature_label = np.array([d['temperature'] for d in data])
ising_data = ising_data[:, np.newaxis, :, :]

# ising_data=np.load('../IsingData/ising_dataset2.npy', allow_pickle=True)
ising_data.shape = -1, 1, imgsize, imgsize
# temperature_label=np.load('../IsingData/labels_dataset2.npy', allow_pickle=True)
dataset = TensorDataset(torch.tensor(ising_data,dtype=torch.float32),torch.tensor(temperature_label,dtype=torch.float32))
dataloader=DataLoader(dataset,batch_size=batch_size,shuffle=True)

model = UNet_conditional().to(device=device)
optimizer = optim.AdamW(model.parameters(), lr=lr)
mse = nn.MSELoss()
diffusion = Diffusion(img_size=imgsize, device=device)

for epoch in range(nepoch):
    pbar = tqdm(dataloader)
    for i, (images, labels) in enumerate(pbar):
        images = images.to(device)
        labels = labels.to(device)
        t = diffusion.sample_timesteps(images.shape[0]).to(device)
        x_t, noise = diffusion.noise_images(images, t)
        predicted_noise = model(x_t, t, labels)
        loss = mse(noise, predicted_noise)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        pbar.set_postfix(MSE=loss.item())

    if epoch % nfreq == 0:
        torch.save(model.state_dict(), f"{epoch}ckpt.pt")

# !python sample.py 3.5


# file = boards_url +'samples_{}.npy'.format(temp)
# files.download(file)

# gensam=np.load('samples_3.5.npy')
# plt.imshow(gensam[7][0], cmap='gray_r',  vmin=-1, vmax=1)
# !cp -r /content/generative_models_Ising/ '/content/drive/MyDrive/DIFUVIA'
